package ua.com.nov.model.entity.database;

import ua.com.nov.model.dao.SqlStatementSource;
import ua.com.nov.model.entity.column.Column;
import ua.com.nov.model.entity.table.Table;
import ua.com.nov.model.entity.table.TableID;

public class HyperSqlDb extends Database {
    private static final SqlStatementSource<DatabaseID, Database>
            DATABASE_SQL_STATEMENT_SOURCE = new HyperSqlDbStmts();
    private static final SqlStatementSource<TableID, Table>
            TABLE_SQL_STATEMENT_SOURCE = new HyperSqlTableStmts();

    public HyperSqlDb(DatabaseID pk) {
        super(pk);
    }

    public HyperSqlDb(String dbUrl, String userName) {
        super(dbUrl, userName);
    }

    public HyperSqlDb(String dbUrl, String userName, String password) {
        super(dbUrl, userName, password);
    }

    public HyperSqlDb(DatabaseID pk, String password) {
        super(pk, password);
    }

    @Override
    public SqlStatementSource<DatabaseID, Database> getSqlStmtSource() {
        return DATABASE_SQL_STATEMENT_SOURCE;
    }

    @Override
    public SqlStatementSource<TableID, Table> getTableSqlStmtSource() {
        return TABLE_SQL_STATEMENT_SOURCE;
    }

    @Override
    public String getDbProperties() {
        return "";
    }

    private static class HyperSqlDbStmts extends AbstractSqlDbStatements {
        @Override
        public String getCreateStmt(Database db) {
           throw new UnsupportedOperationException();
        }

        @Override
        public String getDeleteStmt(Database db) {
            throw new UnsupportedOperationException();
        }
    }

    private static class HyperSqlTableStmts extends AbstractSqlTableStatements {
        @Override
        protected void addFullTypeName(Column col, StringBuilder result) {
            result.append(col.getDataType().getTypeName());
            addSizeAndPrecision(col, result);
            if (col.isAutoIncrement()) {
                if (col.getDataType().isAutoIncrement()) result.append(" GENERATED BY DEFAULT AS IDENTITY");
                else throw new IllegalArgumentException();
            }
        }
    }
}
