package ua.com.nov.model.entity.database;

import ua.com.nov.model.entity.column.Column;

public class HyperSqlDb extends Database {

    public HyperSqlDb(DatabaseID pk) {
        super(pk);
    }

    public HyperSqlDb(String dbUrl, String userName) {
        super(dbUrl, userName);
    }

    public HyperSqlDb(String dbUrl, String userName, String password) {
        super(dbUrl, userName, password);
    }

    public HyperSqlDb(DatabaseID pk, String password) {
        super(pk, password);
    }

    @Override
    public Executable getExecutor() {
        return new HyperSqlExecutor();
    }

    @Override
    public String getDbProperties() {
        return "";
    }

    public class HyperSqlExecutor extends Executor {
        @Override
        protected void addFullTypeName(Column col, StringBuilder result) {
            result.append(col.getDataType().getTypeName());
            addSizeAndPrecision(col, result);
            if (col.isAutoIncrement()) {
                if (col.getDataType().isAutoIncrement()) result.append(" GENERATED BY DEFAULT AS IDENTITY");
                else throw new IllegalArgumentException();
            }
        }
    }

}
