package ua.com.nov.model.entity.metadata.table.column;

import ua.com.nov.model.entity.metadata.server.HyperSqlServer;

import java.util.LinkedList;
import java.util.List;
import java.util.Map;

public class HyperSqlColumnOptions extends ColumnOptions {
    private HyperSqlColumnOptions(Builder builder) {
        super(builder);
    }

    @Override
    public List<String> getUpdateOptionsDefinition() {
        List<String> result = new LinkedList<>();

        if (!isNotNull()) result.add("SET NULL");
        if (getDefaultValue() == null) result.add("DROP DEFAULT");
        if (!isAutoIncrement()) result.add("DROP GENERATED");

        for (Map.Entry<String, String> entry : getOptionsMap().entrySet()) {
            StringBuilder sb = new StringBuilder();
            sb.append("SET ").append(entry.getKey().trim());
            if (!entry.getValue().isEmpty())
                sb.append(' ').append(entry.getValue());
            result.add(sb.toString());
        }
        return result;
    }

    public static class Builder extends ColumnOptions.Builder<HyperSqlColumnOptions> {

        public Builder() {
            super(HyperSqlServer.class);
        }

        @Override
        public HyperSqlColumnOptions build() {
            return new HyperSqlColumnOptions(this);
        }

        @Override
        protected String getAutoIncrementDefinition() {
            return "GENERATED BY DEFAULT AS IDENTITY";
        }
    }
}
