package ua.com.nov.model.entity.metadata.table.column;

import ua.com.nov.model.entity.metadata.server.HsqldbServer;
import ua.com.nov.model.util.CollectionUtils;

import java.util.List;

public class HyperSqlColumnOptions extends ColumnOptions {
    private HyperSqlColumnOptions(Builder builder) {
        super(builder);
    }

    @Override
    public List<String> getUpdateOptionsDefinition() {
        List<String> result = CollectionUtils.toList(getOptionsMap(), " ", "SET");

        if (!isNotNull()) result.add("SET NULL");
        if (getDefaultValue() == null) result.add("DROP DEFAULT");
        if (!isAutoIncrement()) result.add("DROP GENERATED");

        return result;
    }

    public static class Builder extends ColumnOptions.Builder<HyperSqlColumnOptions> {

        public Builder() {
            super(HsqldbServer.class);
        }

        @Override
        public HyperSqlColumnOptions build() {
            return new HyperSqlColumnOptions(this);
        }

        @Override
        protected String getAutoIncrementDefinition() {
            return "GENERATED BY DEFAULT AS IDENTITY";
        }
    }
}
