package ua.com.nov.model.entity.metadata.database;

public class HyperSqlColumnOptions extends ColumnOptions {
    private HyperSqlColumnOptions(Builder builder) {
        super(builder);
    }

    public static class Builder extends ColumnOptions.Builder<HyperSqlColumnOptions> {

        public Builder() {
            super(HyperSqlDb.class);
        }

        @Override
        public HyperSqlColumnOptions build() {
            return new HyperSqlColumnOptions(this);
        }

        @Override
        protected String getAutoIncrementDefinition() {
            return "GENERATED BY DEFAULT AS IDENTITY";
        }
    }
}
