package ua.com.nov.model.entity.metadata.database;

import ua.com.nov.model.entity.Persistent;
import ua.com.nov.model.entity.Unique;
import ua.com.nov.model.entity.metadata.datatype.DataType;
import ua.com.nov.model.entity.metadata.datatype.JdbcDataTypes;
import ua.com.nov.model.entity.metadata.table.Table;
import ua.com.nov.model.entity.metadata.table.column.Column;
import ua.com.nov.model.entity.metadata.table.constraint.ForeignKey;
import ua.com.nov.model.entity.metadata.table.constraint.PrimaryKey;
import ua.com.nov.model.entity.metadata.table.constraint.UniqueKey;
import ua.com.nov.model.statement.*;

import java.sql.Types;
import java.util.ArrayList;
import java.util.List;

public class HyperSqlDb extends Database {

    public HyperSqlDb(String dbUrl, String dbName) {
        super(dbUrl, dbName, null);
        getTypesMap().put(JdbcDataTypes.LONGVARCHAR, "LONGVARCHAR");
        List<DataType> dataTypeList = new ArrayList<>();
        dataTypeList.add(new DataType.Builder("LONGVARCHAR", Types.LONGVARCHAR).build());
        addDataTypes(dataTypeList);
    }

    @Override
    public String getAutoIncrementDefinition() {
        return " GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public String getFullTableName(Table.Id id) {
        StringBuilder result = new StringBuilder();
        if (id.getSchema() != null) result.append(id.getSchema()).append('.');
        return result.append(id.getName()).toString();
    }

    @Override
    public String convert(String parameter) {
        if (parameter != null) return parameter.toUpperCase();
        return parameter;
    }

    @Override
    public AbstractMetaDataSqlStatements getDatabaseSqlStmtSource() {
        return new AbstractMetaDataSqlStatements() {
            @Override
            public SqlStatement getCreateStmt(Unique value) {
                throw new UnsupportedOperationException();
            }

            @Override
            public SqlStatement getUpdateStmt(Unique value) {
                throw new UnsupportedOperationException();
            }

            @Override
            public SqlStatement getDeleteStmt(Persistent key) {
                throw new UnsupportedOperationException();
            }

        };
    }

    @Override
    public AbstractTableSqlStatements getTableSqlStmtSource() {
        return new AbstractTableSqlStatements() {
        };
    }

    @Override
    public AbstractColumnSqlStatements getColumnSqlStmtSource() {
        return new AbstractColumnSqlStatements() {
            @Override
            public SqlStatement getUpdateStmt(Column col) {
                return null;
//                return String.format("ALTER TABLE %s ALTER COLUMN %s RENAME TO %s",
//                        col.getTableId().getFullName(), col.getName(), col.getNewName());
            }
        };
    }

    @Override
    public AbstractConstraintSqlStatements<PrimaryKey> getPrimaryKeySqlStmtSource() {
        return new AbstractConstraintSqlStatements<PrimaryKey>(){};
    }

    @Override
    public AbstractConstraintSqlStatements<ForeignKey> getForeignKeySqlStmtSource() {
        return new AbstractConstraintSqlStatements<ForeignKey>(){};
    }

    @Override
    public AbstractConstraintSqlStatements<UniqueKey> getUniqueKeySqlStmtSource() {
        return new AbstractConstraintSqlStatements<UniqueKey>() {};
    }

    @Override
    public AbstractIndexSqlStatements getIndexSqlStmtSource() {
        return new AbstractIndexSqlStatements(){};
    }
}
